Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2021-11, with the labels that each got.

#371 fix: RDCC-3557 Upgraded spring core version to fix CVE-2021-22096
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-371

#366 Upgrade TF and AzureRM versions
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-366

#373 feat: RDCC-3540 Upload Template Improvements
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/client/CaseWorkerApiClient.java
  src/functionalTest/resources/Staff Data Upload with non idam roles.xlsx
  src/functionalTest/resources/Staff Data Upload.xls
  src/functionalTest/resources/Staff Data Upload.xlsx
  src/functionalTest/resources/Staff_Data_Upload_with_non_idam_roles.xls
  src/integrationTest/resources/Staff Data Test incorrect function.xlsx
  src/integrationTest/resources/Staff Data Upload Update.xlsx
  src/integrationTest/resources/Staff Data Upload With All Empty Rows.xlsx
  src/integrationTest/resources/Staff Data Upload With All Valid Rows.xlsx
  src/integrationTest/resources/Staff Data Upload With Case Insensitive Email.xlsx
  src/integrationTest/resources/Staff Data Upload With Duplicate Email Profiles.xlsx
  src/integrationTest/resources/Staff Data Upload With Jsr.xlsx
  src/integrationTest/resources/Staff Data Upload With Name Longer Than 128 and Name With Invalid Character.xlsx
  src/integrationTest/resources/Staff Data Upload With Some Empty Rows.xlsx
  src/integrationTest/resources/Staff Data Upload Xls.xls
  src/integrationTest/resources/Staff Data Upload Xlsx With Only Header.xlsx
  src/integrationTest/resources/Staff Data Upload with non idam roles.xls
  src/integrationTest/resources/Staff Data Upload with non idam roles.xlsx
  src/integrationTest/resources/Staff Data Upload.xlsx
  src/integrationTest/resources/StaffData Upload Suspended.xlsx
  src/integrationTest/resources/application-test.yml
  src/integrationTest/resources/db/testmigration/V1_2__insert_queries_role_user_type.sql
  src/main/java/uk/gov/hmcts/reform/cwrdapi/client/domain/WorkArea.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_12__update_usertype.sql
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelAdaptorServiceImplTest.java
  src/test/resources/Staff Data Upload With Empty Rows.xlsx
  src/test/resources/Staff Data Upload With Formula.xlsx
  src/test/resources/Staff Data Upload With Jsr.xlsx
  src/test/resources/Staff Data Upload.xls
  src/test/resources/Staff Data Upload.xlsx
  src/test/resources/Staff Data UploadWithInvalidHeaders.xls
  src/test/resources/Staff Data Upload_WithNoValidSheetName.xlsx
  src/test/resources/Staff Data Upload_WithXlsxOnlyHeader.xlsx
Labels: ns:rd, prd:rd, DO NOT MERGE, rel:rd-caseworker-ref-api-pr-373

#374 Publish Jenkins tests reports
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-374

#375 fix: RDCC-3634 Replaced the deprecated method and added the valid method in use
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/counter/TestCountListener.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/SerenityPageExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/FileUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/IntegrationTestOidcSecurityConfig.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/counter/TestCountListener.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/SerenityPageExtension.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-375
