Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2021-07, with the labels that each got.

#338 fixed the security scan
  security.sh
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-338

#337 Add auto-update config for PR branches
  .github/workflows/autoupdate.yml
Labels: DO NOT MERGE, ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-337

#339 fix: RDCC-3047 Fixed PACTs not being verified issue
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-339

#340 fixed cvv
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-340

#341 fix: Remove bintray reference(RDCC-3150)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-341

#342 fix:RDCC-3167 Upgraded the commons-compress to address CVE-2021-35515 CVE-2021-35516, CVE-2021-35517, CVE-2021-36090
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-342

#344 fix: RDCC-2820 Fixed failing test due to changes in UP email removal
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/client/FuncTestRequestHandler.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-344
