Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2022-09, with the labels that each got.

#545 fix: Fixed the failing test by providing invalid ccd service name
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-545

#549 staff ui tables script
  src/integrationTest/resources/db/testmigration/V1_17__staff_ui_tables.sql
  src/main/resources/db/migration/V1_17__staff_ui_tables.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-549

#553 RDCC-5447: Suppress Snakeyaml CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-553

#567 Nightly Fix: Updating security.sh
  security.sh
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-567

#558 RDCC-5417 - Controller, service, serviceImpl, JunitTest cases, Functional Test Case, PACT Test Cases, Sonar Violation fixes
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefUserTypeFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/client/CaseWorkerApiClient.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/idam/IdamOpenIdClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/response/StaffRefDataUserType.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/response/StaffRefDataUserTypesResponse.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/StaffRefDataService.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/FeatureToggleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/response/StaffRefDataUserTypesResponseTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-558
