Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2022-05, with the labels that each got.

#487 fix: RDCC-4633 Fixed CVE CVE-2022-25647 by upgrading gson and LD
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-487

#484 Feat:Changes made to fix app-insights issue
  Dockerfile
  build.gradle
  docker-compose.yml
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelAdaptorServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/util/JsonFeignResponseUtilTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-484

#489 fix: RDCC-4670 Fixed CVE-2022-24823 by upgrading netty
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-489

#490 RDCC-4614:Changes made to fix sonar issues
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefUsersController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-490

#493 RDCC-4690: Suppressing CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-493

#494 CVEFix for tomcat embed
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-494

#495 RDCC-4700 :SRD Nightly Build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-495

#496 RDCC-4614:Changes made to fix logger issues
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-496

#499 fix: Bumped spring dependencies version to 5.3.20
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-499

#501 feat: Added multi-architecture ACR Task template
  Dockerfile
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-501
