Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2022-08, with the labels that each got.

#531 fix: RDCC-5181 Fixed the failing functional test case
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-531

#529 fix cve removed suppressions
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-529

#535 Feat:RDCC-5178:Changes made to sync flywayscripts
  src/integrationTest/resources/db/testmigration/V1_12__update_usertype.sql
  src/integrationTest/resources/db/testmigration/V1_16__update_roletype.sql
  src/integrationTest/resources/db/testmigration/V1_7__insert_update_queries_role_type.sql
  src/integrationTest/resources/db/testmigration/V1_8__insert_queries_role_type.sql
  src/integrationTest/resources/db/testmigration/V1_9__insert_queries_role_types.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-535

#536 RDCC-5261: Upgrading postgresql to 42.4.1
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-536

#533 RDCC-5182 fix for version compare in SRD file
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/rd-caseworker-ref-api/Chart.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
  src/functionalTest/resources/Staff Data Upload different Version.xlsx
  src/functionalTest/resources/Staff Data Upload with non idam roles.xlsx
  src/functionalTest/resources/Staff Data Upload.xls
  src/functionalTest/resources/Staff Data Upload.xlsx
  src/functionalTest/resources/Staff_Data_Upload_with_non_idam_roles.xls
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerCreateUserWithFileUploadTest.java
  src/integrationTest/resources/Staff Data Test incorrect function.xlsx
  src/integrationTest/resources/Staff Data Upload No Version Sheet.xlsx
  src/integrationTest/resources/Staff Data Upload No Version.xlsx
  src/integrationTest/resources/Staff Data Upload Update.xlsx
  src/integrationTest/resources/Staff Data Upload With All Empty Rows.xlsx
  src/integrationTest/resources/Staff Data Upload With All Valid Rows.xlsx
  src/integrationTest/resources/Staff Data Upload With Case Insensitive Email.xlsx
  src/integrationTest/resources/Staff Data Upload With Duplicate Email Profiles.xlsx
  src/integrationTest/resources/Staff Data Upload With Jsr.xlsx
  src/integrationTest/resources/Staff Data Upload With Name Longer Than 128 and Name With Invalid Character.xlsx
  src/integrationTest/resources/Staff Data Upload With Some Empty Rows.xlsx
  src/integrationTest/resources/Staff Data Upload Xls.xls
  src/integrationTest/resources/Staff Data Upload Xlsx With Only Header.xlsx
  src/integrationTest/resources/Staff Data Upload different Version.xlsx
  src/integrationTest/resources/Staff Data Upload with non idam roles.xls
  src/integrationTest/resources/Staff Data Upload with non idam roles.xlsx
  src/integrationTest/resources/Staff Data Upload.xlsx
  src/integrationTest/resources/StaffData Upload Suspended.xlsx
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/ExcelAdaptorServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelAdaptorServiceImplTest.java
  src/test/resources/Staff Data Upload No Version Sheet.xlsx
  src/test/resources/Staff Data Upload No Version.xlsx
  src/test/resources/Staff Data Upload With Empty Rows.xlsx
  src/test/resources/Staff Data Upload With Formula.xlsx
  src/test/resources/Staff Data Upload different Version.xlsx
  src/test/resources/Staff Data Upload.xlsx
  src/test/resources/Staff Data UploadWithInvalidHeaders.xls
  src/test/resources/Staff Data Upload_WithNoValidSheetName.xlsx
  src/test/resources/Staff Data Upload_WithXlsxOnlyHeader.xlsx
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-533

#540 Add backstage configuration file
  catalog-info.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-540

#544 Revert "RDCC-5182 fix for version compare in SRD file"
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/rd-caseworker-ref-api/Chart.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
  src/functionalTest/resources/Staff Data Upload different Version.xlsx
  src/functionalTest/resources/Staff Data Upload with non idam roles.xlsx
  src/functionalTest/resources/Staff Data Upload.xls
  src/functionalTest/resources/Staff Data Upload.xlsx
  src/functionalTest/resources/Staff_Data_Upload_with_non_idam_roles.xls
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerCreateUserWithFileUploadTest.java
  src/integrationTest/resources/Staff Data Test incorrect function.xlsx
  src/integrationTest/resources/Staff Data Upload No Version Sheet.xlsx
  src/integrationTest/resources/Staff Data Upload No Version.xlsx
  src/integrationTest/resources/Staff Data Upload Update.xlsx
  src/integrationTest/resources/Staff Data Upload With All Empty Rows.xlsx
  src/integrationTest/resources/Staff Data Upload With All Valid Rows.xlsx
  src/integrationTest/resources/Staff Data Upload With Case Insensitive Email.xlsx
  src/integrationTest/resources/Staff Data Upload With Duplicate Email Profiles.xlsx
  src/integrationTest/resources/Staff Data Upload With Jsr.xlsx
  src/integrationTest/resources/Staff Data Upload With Name Longer Than 128 and Name With Invalid Character.xlsx
  src/integrationTest/resources/Staff Data Upload With Some Empty Rows.xlsx
  src/integrationTest/resources/Staff Data Upload Xls.xls
  src/integrationTest/resources/Staff Data Upload Xlsx With Only Header.xlsx
  src/integrationTest/resources/Staff Data Upload different Version.xlsx
  src/integrationTest/resources/Staff Data Upload with non idam roles.xls
  src/integrationTest/resources/Staff Data Upload with non idam roles.xlsx
  src/integrationTest/resources/Staff Data Upload.xlsx
  src/integrationTest/resources/StaffData Upload Suspended.xlsx
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/ExcelAdaptorServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelAdaptorServiceImplTest.java
  src/test/resources/Staff Data Upload No Version Sheet.xlsx
  src/test/resources/Staff Data Upload No Version.xlsx
  src/test/resources/Staff Data Upload With Empty Rows.xlsx
  src/test/resources/Staff Data Upload With Formula.xlsx
  src/test/resources/Staff Data Upload different Version.xlsx
  src/test/resources/Staff Data Upload.xlsx
  src/test/resources/Staff Data UploadWithInvalidHeaders.xls
  src/test/resources/Staff Data Upload_WithNoValidSheetName.xlsx
  src/test/resources/Staff Data Upload_WithXlsxOnlyHeader.xlsx
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-544

#538 Refactor code to remove the hard coding
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-538
