Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2022-11, with the labels that each got.

#595 Rdcc 5448 -Advance Search
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataAdvancedSearchFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceProfileAdvanceIntegrationSearchTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/client/domain/Location.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/config/WebMvcConfig.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/EmptyRequestException.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/ExceptionMapper.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/constants/ErrorConstants.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/request/SearchRequest.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/CaseWorkerSkill.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/UserType.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/repository/CaseWorkerProfileRepository.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/StaffRefDataService.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/FeatureToggleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/RequestUtils.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/TestSupport.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/request/SearchRequestTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/repository/CaseWorkerProfileRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-595

#613 RDCC-5778: Upgrading `tomcat` to version `9.0.68`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-613

#615 Feat:RDCC-5674:Changes made to add add container based integration test cases
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/service/ValidationServiceFacadeImplTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseworkerRefApiPostgresqlContainer.java
  src/integrationTest/resources/application-test.yml
  src/integrationTest/resources/db/testmigration/V1_10__add_case_allocator_task_supervisor_columns.sql
  src/integrationTest/resources/db/testmigration/V1_11__insert_queries_role_user_type.sql
  src/integrationTest/resources/db/testmigration/V1_12__update_usertype.sql
  src/integrationTest/resources/db/testmigration/V1_13__update_roletype.sql
  src/integrationTest/resources/db/testmigration/V1_14__insert_roletype.sql
  src/integrationTest/resources/db/testmigration/V1_15__insert_roletype.sql
  src/integrationTest/resources/db/testmigration/V1_17__staff_ui_tables.sql
  src/integrationTest/resources/db/testmigration/V1_1__init_tables.sql
  src/integrationTest/resources/db/testmigration/V1_2__add_sequences.sql
  src/integrationTest/resources/db/testmigration/V1_2__insert_queries_role_user_type.sql
  src/integrationTest/resources/db/testmigration/V1_3__insert_queries_role_user_type.sql
  src/integrationTest/resources/db/testmigration/V1_5__add_case_allocator_task_supervisor_columns.sql
  src/integrationTest/resources/db/testmigration/V1_5__remove_delete_date_column.sql
  src/integrationTest/resources/db/testmigration/V1_6__alter_exception.sql
  src/integrationTest/resources/db/testmigration/V1_6__insert_queries_role_user_type.sql
  src/integrationTest/resources/db/testmigration/V1_7__update_queries_role_type.sql
  src/integrationTest/resources/db/testmigration/V1_8__alter_excpetion_key.sql
  src/integrationTest/resources/db/testmigration/V1_8__insert_queries_role_type.sql
  src/integrationTest/resources/db/testmigration/V1_9__alter_audit_userid.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-615

#616 adding missed test cases for advanced search api
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerProfileRepositoryIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceProfileAdvanceIntegrationSearchTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-616

#618 Feat:SRD: Staff update Integration test cases
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/UpdateStaffReferenceProfileTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-618

#619 Create staff integration test cases
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-619

#621 Upgrade Terraform version 1.3.X :: RDCC-5894
  infrastructure/.terraform-version
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-621

#622 Fixing nightly build - ignoring owasp scan for new api's
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-622

#624 Fixing nightly build - ignoring owasp scan for new api's
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-624

#625 Nightly build fix
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-625

#626 Create Replica database for Staff in Production
  infrastructure/prod.tfvars
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-626

#627 Nightly Build Fix: Adding Entries to audit.json
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-627

#628 Nightly Fix: Adding entries to audit.json
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-628

#634 cve fix issue
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-634
