Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2022-06, with the labels that each got.

#500 Fea:To handle 500 HTTP responses
  src/main/java/uk/gov/hmcts/reform/cwrdapi/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/config/SecurityEndpointFilter.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/UnauthorizedException.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/repository/IdamRepository.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/advice/UnauthorizedExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/repository/IdamRepositoryTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-500

#507 Feat:RDCC-4676:Changes made to Auto merge depend Bot script w.r.t Renovate
  .github/workflows/combine-prs.yml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-507

#506 RDCC-4849: Collating DependaBot PRs
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-506

#519 RDCC-4898 Delete dependabot yaml file
  .github/dependabot.yml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-519

#522 RDCC-5005: Update the chart version of service bus and blob storage to the latest
  charts/rd-caseworker-ref-api/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-522
