Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2022-04, with the labels that each got.

#450 Rdcc 4134-SRD: Add new roles and user type for SSCS Hearings
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
  src/functionalTest/resources/Staff Data Upload with non idam roles.xlsx
  src/functionalTest/resources/Staff Data Upload.xls
  src/functionalTest/resources/Staff Data Upload.xlsx
  src/functionalTest/resources/Staff_Data_Upload_with_non_idam_roles.xls
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateCaseWorkerProfilesIntegrationTest.java
  src/integrationTest/resources/ServiceToIDAMRoleMapping_newRoles.xlsx
  src/integrationTest/resources/Staff Data Upload Update.xlsx
  src/integrationTest/resources/Staff Data Upload With All Empty Rows.xlsx
  src/integrationTest/resources/Staff Data Upload With All Valid Rows.xlsx
  src/integrationTest/resources/Staff Data Upload With Case Insensitive Email.xlsx
  src/integrationTest/resources/Staff Data Upload With Duplicate Email Profiles.xlsx
  src/integrationTest/resources/Staff Data Upload With Jsr.xlsx
  src/integrationTest/resources/Staff Data Upload With Name Longer Than 128 and Name With Invalid Character.xlsx
  src/integrationTest/resources/Staff Data Upload Xls.xls
  src/integrationTest/resources/Staff Data Upload with non idam roles.xls
  src/integrationTest/resources/Staff Data Upload with non idam roles.xlsx
  src/integrationTest/resources/Staff Data Upload.xlsx
  src/integrationTest/resources/StaffData Upload Suspended.xlsx
  src/integrationTest/resources/db/testmigration/V1_8__insert_queries_role_type.sql
  src/main/resources/db/migration/V1_14__insert_roletype.sql
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefUsersControllerTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-450

#473 (DEMO) RDCC-4363: adding step enableDbMigration('rd') in Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-473

#474 RDCC-4363: adding POSTGRES-DATABASE secret to main.tf
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-474

#477 RDCC-4427: CVE fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-477

#469 Add New Role for sscs role type
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateCaseWorkerProfilesIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_9__insert_queries_role_types.sql
  src/main/resources/db/migration/V1_15__insert_roletype.sql
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefUsersControllerTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-469

#472 RDCC-4363: Externalise the DB Migration Step in Build Pipeline
  Jenkinsfile_CNP
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-472

#479 Fix Sonar Issue in SRD
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelAdaptorServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/ValidationServiceFacadeTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/FeatureToggleServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-479

#480 SRD Nightly build failure -25/04/2022
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-480

#471 use of rd-commons-lib in to case worker ref api
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/WelcomeFuncTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/SerenityTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/SerenityTestWithoutReporting.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/counter/TestCountListener.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/counter/TestCounter.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityJUnitLifecycleAdapterExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityManualExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityReportExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityStepExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/PatchedManagedWebDriverAnnotatedField.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/SerenityPageExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/TestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/TestMethodAnnotations.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/guice/JUnit5Module.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/guice/JUnitInjectors.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/service/ExcelUploaderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/service/ValidationServiceFacadeImplTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/SerenityTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/SerenityTestWithoutReporting.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/counter/TestCountListener.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/counter/TestCounter.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityJUnitLifecycleAdapterExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityManualExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityReportExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/SerenityStepExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/PatchedManagedWebDriverAnnotatedField.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/SerenityPageExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/TestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/extension/page/TestMethodAnnotations.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/guice/JUnit5Module.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/serenity5/guice/JUnitInjectors.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-471
