Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2022-12, with the labels that each got.

#636 CVE-2021-37533 Issue Suppression : RDCC - 6007
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-636

#637 RDCC-6061: Adding Suppression for `CVE-2022-41881`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-637

#638 RDCC-6073: Fix for `CVE-2022-41915`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-638
