Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2023-02, with the labels that each got.

#653 RDCC-6259: Adding & Upgrading Dependencies
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-653

#654 Staff : Update skill table with the new skills for PrL
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefCreateFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataSkillsFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerProfileRepositoryIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceProfileAdvanceIntegrationSearchTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/UpdateStaffReferenceProfileTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
  src/integrationTest/resources/db/testmigration/V1_18__update_skill_table.sql
  src/main/resources/db/migration/V1_19__update_skill_table.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-654

#657 RDCC-6226: Update flyway script with delete statement
  src/integrationTest/resources/db/testmigration/V1_18__update_skill_table.sql
  src/main/resources/db/migration/V1_19__update_skill_table.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-657

#658 RDCC-6332: Fix for CVE-2022-40152
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-658

#662 RDCC-1707: Upgrade helm chart version to latest
  charts/rd-caseworker-ref-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-662

#664 RDCC-6374: Upgrading chart version to `4.0.13`
  charts/rd-caseworker-ref-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-664

#667 RDCC-6432: Adding Suppression for `CVE-2022-45688`
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-667
