Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2023-09, with the labels that each got.

#758 Fix CVE-2023-39533
  .github/renovate.json
  Jenkinsfile_CNP
  build.gradle
  charts/rd-caseworker-ref-api/values.preview.template.yaml
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-caseworker-ref-api-pr-758

#759 CVE CVE-2022-26336 suppression
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-759

#760 CVE fix
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-760

#762 DTSRD-1173.Nightly builds failing with OWASP Zaproxy error
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-762

#764 DTSRD-1173.Nightly builds failing with OWASP Zaproxy error
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-764
