Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2023-04, with the labels that each got.

#693 RDCC-6526: Pact Test Coverage for Fetch StaffProfileByID endpoint
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-693

#704 CRD CVE Suppression
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-704

#703 DTSRD-84: update URLs for Preview and AAT
  Jenkinsfile_CNP
  security.sh
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-703

#702 Upped spring framework version to fix CVE-2023-20860
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-702

#705 Remove CVE-2023-20861 as fixed by spring version bump
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-705

#706 Ignore warnings from nightly build
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-706

#700 [RDCC-6255]SRD : Update Skills for Family Private Law
  src/integrationTest/resources/db/testmigration/V1_19__update_skill_table.sql
  src/main/resources/db/migration/V1_20__update_skill_table.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-700

#707 DTSRD-202 - suppress 10096_Timestamp for robots.txt GET
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-707

#708 Rdcc 6688 basic search first and last name
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileBasicSearchTest.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/repository/CaseWorkerProfileRepository.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/RequestUtils.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataJobTitleControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-708

#709 RDCC-6688 : Search API assertion changed for shouldFetchStaffProfileB…
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-709

#711 DTSRD-223 - update audit.json for 10096_Timestamp Disclosure
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-711

#712 RDCC-6697 : Search by name API regex correction
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataAdvancedSearchFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileBasicSearchTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/JsrValidatorStaffProfileTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/util/RequestUtilsTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-712

#715 Addresses CVE-2023-20863
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-715
