Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2023-05, with the labels that each got.

#697 Upgrade gradle wrapper to 7.4.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-697

#717 addresses CVE-2023-20873, CVE-2023-20862
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-717

#720 To Delete test skills in skill table
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/FetchStaffProfileByIdFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefCreateFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataSkillsFunctionalTest.java
  src/main/resources/db/migration/V1_21__Delete_skill_TestSkill.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-720

#719 [RDCC-6200]-Delete functional Test Data - Staff Reference Data
  Jenkinsfile_nightly
  deletescript/delete-functional-data.sh
  deletescript/sql/delete-functional-test-data.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-719

#716 Remove StaffAdminrole from Idam
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefUpdateProfileFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/idam/IdamOpenIdClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/UpdateStaffReferenceProfileTest.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/client/domain/RoleDeletionResponse.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/client/domain/UserProfileRolesResponse.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/domain/UserProfileUpdatedData.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataUpdateStaffServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-716

#723 [RDCC-6750]Staff UI : Add new Skills for Family Private Law
  src/main/resources/db/migration/V1_22__update_skill_table.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-723

#724 [RDCC-6200] Fix for delete functional test user
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-724

#726 [RDCC-6200] Fix for delete functional test user
  Jenkinsfile_nightly
  src/functionalTest/resources/application-functional.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-726

#727 [RDCC-6200] Sql query to delete functional test users from diff tables
  deletescript/sql/delete-functional-test-data.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-727

#728 [RDCC-6200] Sql query to delete functional test users from skill table
  deletescript/sql/delete-functional-test-data.sql
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-728

#725 SRD: Test Cases can be clubbed as Parameterised tests
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/CaseWorkerProfileConverterTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerDeleteServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-725

#721 Update users regardless of active status
  charts/rd-caseworker-ref-api/Chart.yaml
  charts/rd-caseworker-ref-api/values.preview.template.yaml
  config/owasp/suppressions.xml
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefUpdateProfileFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/feign/UserProfileFeignClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataUpdateStaffServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-721
