Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2023-03, with the labels that each got.

#663 Feat:Staff : Filter the list of Skills based on Service Code
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/repository/SkillRepository.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/StaffRefDataService.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/RequestUtils.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-663

#666 RDCC-6421-renovate.json update
  .github/renovate.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-666

#670 security scan issues
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-670

#671 Rdcc 6212
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/UpdateStaffReferenceProfileTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/request/StaffProfileCreationRequest.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/StaffRefDataService.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataUserProfileControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-671

#665 Fetch Staff Profile By Id
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/FetchStaffProfileByIdFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/FetchStaffProfileByIdIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/config/WebMvcConfig.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/feign/UserProfileFeignClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/response/SearchStaffUserByIdResponse.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/StaffRefDataService.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/FeatureToggleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-665

#684 Revert "addressed security scan issues"
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-684

#685 addressed security scan issues
  audit.json
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-685

#689 RDCC-6470 Upgrade Libs
  build.gradle
  infrastructure/.terraform-version
  infrastructure/terraform.tf
  src/test/java/uk/gov/hmcts/reform/cwrdapi/repository/IdamRepositoryTest.java
Labels: ns:rd, prd:rd, no-changes, rel:rd-caseworker-ref-api-pr-689

#688 RDCC-6429: Address CVEs in all Reference Data repositories - Staff Reference Data
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-688

#694 RDCC-6611: suppress CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-694

#687 addresses Idam returning user with null roles assigned
  src/main/java/uk/gov/hmcts/reform/cwrdapi/oidc/JwtGrantedAuthoritiesConverter.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/oidc/JwtGrantedAuthoritiesConverterTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-687

#696 Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-696

#698 RDCC-6599: update URLs for Preview and AAT
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-698
