Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2023-11, with the labels that each got.

#800 Update application.yaml to add schema to connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-800

#802 Update application.yaml. reverting connection string
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-802

#803 DTSRD-1466.Updating schema parameter with hibernate
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-803

#714 RDCC-6706 SRD:WireMock response enhancement
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/IntegrationTestOidcSecurityConfig.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/UserIdentifier.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/WireMockUtil.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-714

#710 Feat:SRD- Test coverage
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/UpdateStaffReferenceProfileTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/response/StaffRefDataUserType.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/repository/RoleTypeRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/repository/SkillRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/repository/UserTypeRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-710

#801 [RDCC-7097]UP : Consumer Pact Test Cases needs to be added
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/UserProfileConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/request/DeleteUserProfilesRequest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-801

#805 flyway schema change
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-805

#804 Update acb.tpl.yaml
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-804

#806 Suppress CVE-2023-36052
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-806
