Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2023-10, with the labels that each got.

#775 DTSRD-1245 upgrade postgres
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, add-or-update, rel:rd-caseworker-ref-api-pr-775

#779 DTSRD-1456
  build.gradle
  charts/rd-caseworker-ref-api/Chart.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-779

#783 DTSRD-1446.Remove branches to sync -caseworker demo and master
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-783

#784 DTSRD-1446.Remove branches to sync -caseworker demo
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-784

#787 Addresses CVE-2023-42794, CVE-2023-42795 and CVE-2023-45648
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-787

#795 suppress CVE-2023-5072
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-795

#796 DTSRD-1456.suppressing as no known netty handler version available without vulnerability
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-796

#794 [RDCC-7094]-Judicial : Consumer Pact Test Cases needs to be added
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/JrdUserRequestV1ConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/JrdUserRequestV2ConsumerTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-794

#798 [RDCC-7093]Common : Consumer Pact Test Cases needs to be added
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/CommonDataApiConsumerTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-798

#792 Staff : Block Staff upload Template
  charts/rd-caseworker-ref-api/Chart.yaml
  charts/rd-caseworker-ref-api/values.preview.template.yaml
  charts/rd-caseworker-ref-api/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceFacadeImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerConstants.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceFacadeImplTest.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-caseworker-ref-api-pr-792
