Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2024-06, with the labels that each got.

#873 DTSRD-2801
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-873

#874 Update azurerm to 3.105.0
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-caseworker-ref-api-pr-874

#875 DTSRD-2895
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-caseworker-ref-api-pr-875

#876 DTSRD-2845: Resize PG flexible server instance
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-caseworker-ref-api-pr-876
