Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2024-10, with the labels that each got.

#934 Fix flyway migration issue
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-934

#945 Nightly build failure - increase Pitest log level
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-945

#946 Nightly build failure
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-946

#971 Update build.gradle
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-971

#953 DTSRD-3477 Fix local DependencyCheck, version upgraded to 10.0.3
  build.gradle
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-caseworker-ref-api-pr-953

#981 DTSRD-3545 Fix Branch Pipelines - json-smart exclude
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-981

#982 Dtsrd 3562 swagger publishing
  .github/workflows/swagger.yml
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/docs/SwaggerPublisherTest.java
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-982

#983 DTSRD-3580 Jenkins Test Reports to Publish on Failure - afterSuccess(…
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-983

#984 DTSRD-3623
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-984

#986 DTSRD-3583 PI Test Version Config - pitestVersion added to pitest con…
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-986

#985 DTSRD-3619
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-985
