Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2024-07, with the labels that each got.

#877 DTSRD-3041
  src/main/resources/testcontainers.properties
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-877

#879 Dtsrd 3090
  charts/rd-caseworker-ref-api/Chart.yaml
  infrastructure/.terraform-version
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-caseworker-ref-api-pr-879

#878 Dtsrd 3041
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-878

#901 Update build.gradle. Fix build
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-901

#906 Cleanup - delete testcontainers.properties
  src/main/resources/testcontainers.properties
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-906
