Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2024-05, with the labels that each got.

#851 Update Schema
  infrastructure/main.tf
Labels: ns:rd, prd:rd, aat/destroy, prod/destroy, rel:rd-caseworker-ref-api-pr-851

#852 Update schema ownership 1
  infrastructure/main.tf
Labels: ns:rd, prd:rd, aat/destroy, prod/destroy, rel:rd-caseworker-ref-api-pr-852

#848 Ignore case when searching for case worker by email
  build.gradle
  config/checkstyle/checkstyle.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateCaseWorkerProfilesIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateUpdateStaffRefDataProfilesIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/DeleteCaseWorkerProfilesIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceProfileAdvanceIntegrationSearchTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/UpdateStaffReferenceProfileTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/CaseWorkerRefUsersController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/feign/LocationReferenceDataFeignClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/feign/UserProfileFeignClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/internal/StaffReferenceInternalController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/repository/CaseWorkerProfileRepository.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/repository/CaseWorkerProfileRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataServiceTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/StaffRefDataUpdateStaffServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-848, enable_full_functional_tests

#856 Dtsrd 2752
  src/integrationTest/resources/Staff Data Upload With All Valid Rows.xlsx
  src/integrationTest/resources/Staff Data Upload With Some Empty Rows.xlsx
  src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/StaffProfileCreateUpdateUtil.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/util/StaffProfileCreateUpdateUtilTest.java
Labels: ns:rd, prd:rd, enable_full_functional_tests, rel:rd-caseworker-ref-api-pr-856

#862 Dtsrd 2766
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-862

#857 DTSRD-2750.Dcommissioning single servers
  charts/rd-caseworker-ref-api/Chart.yaml
  charts/rd-caseworker-ref-api/values.yaml
  infrastructure/main.tf
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/destroy, prod/destroy, rel:rd-caseworker-ref-api-pr-857

#863 Update build.gradle - upgrade flyway-fixing master build
  build.gradle
  database/Dockerfile
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseworkerRefApiPostgresqlContainer.java
  src/integrationTest/resources/application-test.yml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-863

#866 Fix DB Migration issues
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-866

#867 Fix db issue
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-867

#871 create replica server
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-caseworker-ref-api-pr-871
