Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2025-05, with the labels that each got.

#1044 DTSRD-4101
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-1044

#1045 DTSRD-4521.Extend email domain list to include IBCA users
  src/integrationTest/resources/application-test.yml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-1045

#1048 DTSRD-4521.Extend email domain list to include IBCA users
  charts/rd-caseworker-ref-api/values.preview.template.yaml
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-1048

#1047 DTSRD-4522
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-1047

#1049 DTSRD-4521-1.Extend email domain list to include IBCA users
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefCreateFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/client/CaseWorkerApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/CreateStaffReferenceProfileIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-caseworker-ref-api-pr-1049

#1050 DTSRD-4101
  Jenkinsfile_nightly
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-caseworker-ref-api-pr-1050
