Repository hmcts/rd-caseworker-ref-api, pull requests merged in 2025-01, with the labels that each got.

#999 CME-297: Update azurerm
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-caseworker-ref-api-pr-999

#1005 Update to spring-boot 3.3.7
  build.gradle
Labels: ns:rd, prd:rd

#993 Cme 196 bump rd commons lib
  Dockerfile
  README.md
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/CommonDataApiConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/JrdUserRequestV1ConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/JrdUserRequestV2ConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/LocationReferenceDataConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/StaffReferenceDataProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/cwrdapi/UserProfileConsumerTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/FetchStaffProfileByIdFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefCreateFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataAdvancedSearchFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataBasicSearchFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefDataSkillsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefJobTitleFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefUpdateProfileFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/StaffRefUserTypeFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/WelcomeFuncTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/client/CaseWorkerApiClient.java
  src/functionalTest/java/uk/gov/hmcts/reform/cwrdapi/util/FeatureToggleConditionExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/docs/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/service/ValidationServiceFacadeImplTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/AuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/cwrdapi/util/CaseWorkerReferenceDataClient.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/CaseWorkerRefApiApplication.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataController.java
  src/main/java/uk/gov/hmcts/reform/cwrdapi/util/RequestUtils.java
  src/smokeTest/java/uk/gov/hmcts/reform/cwrdapi/SmokeTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/controllers/StaffRefDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/domain/CaseWorkerProfileTest.java
  src/test/java/uk/gov/hmcts/reform/cwrdapi/service/impl/CaseWorkerServiceFacadeImplTest.java
  web.config
Labels: ns:rd, prd:rd, enable_keep_helm, rel:rd-caseworker-ref-api-pr-993
